python extract.py \
    headerpp_audio.json \
    ../dylib-hook/libhook.mm \
    ../../header-processing/cfgs/audio_blacklist \
    ../workdir/headerpp/Frameworks/AudioToolbox.framework/Headers/AUAudioUnit.h \
    ../workdir/headerpp/Frameworks/AudioToolbox.framework/Headers/AUAudioUnitImplementation.h \
    ../workdir/headerpp/Frameworks/AudioToolbox.framework/Headers/AUCocoaUIView.h \
    ../workdir/headerpp/Frameworks/AudioToolbox.framework/Headers/AUComponent.h \
    ../workdir/headerpp/Frameworks/AudioToolbox.framework/Headers/AUGraph.h \
    ../workdir/headerpp/Frameworks/AudioToolbox.framework/Headers/AUMIDIController.h \
    ../workdir/headerpp/Frameworks/AudioToolbox.framework/Headers/AUParameters.h \
    ../workdir/headerpp/Frameworks/AudioToolbox.framework/Headers/AudioCodec.h \
    ../workdir/headerpp/Frameworks/AudioToolbox.framework/Headers/AudioComponent.h \
    ../workdir/headerpp/Frameworks/AudioToolbox.framework/Headers/AudioConverter.h \
    ../workdir/headerpp/Frameworks/AudioToolbox.framework/Headers/AudioFile.h \
    ../workdir/headerpp/Frameworks/AudioToolbox.framework/Headers/AudioFileComponent.h \
    ../workdir/headerpp/Frameworks/AudioToolbox.framework/Headers/AudioFileStream.h \
    ../workdir/headerpp/Frameworks/AudioToolbox.framework/Headers/AudioFormat.h \
    ../workdir/headerpp/Frameworks/AudioToolbox.framework/Headers/AudioHardwareService.h \
    ../workdir/headerpp/Frameworks/AudioToolbox.framework/Headers/AudioOutputUnit.h \
    ../workdir/headerpp/Frameworks/AudioToolbox.framework/Headers/AudioQueue.h \
    ../workdir/headerpp/Frameworks/AudioToolbox.framework/Headers/AudioServices.h \
    ../workdir/headerpp/Frameworks/AudioToolbox.framework/Headers/AudioSession.h \
    ../workdir/headerpp/Frameworks/AudioToolbox.framework/Headers/AudioToolbox.h \
    ../workdir/headerpp/Frameworks/AudioToolbox.framework/Headers/AudioUnit.h \
    ../workdir/headerpp/Frameworks/AudioToolbox.framework/Headers/AudioUnitCarbonView.h \
    ../workdir/headerpp/Frameworks/AudioToolbox.framework/Headers/AudioUnitParameters.h \
    ../workdir/headerpp/Frameworks/AudioToolbox.framework/Headers/AudioUnitProperties.h \
    ../workdir/headerpp/Frameworks/AudioToolbox.framework/Headers/AudioUnitUtilities.h \
    ../workdir/headerpp/Frameworks/AudioToolbox.framework/Headers/AudioWorkInterval.h \
    ../workdir/headerpp/Frameworks/AudioToolbox.framework/Headers/CAFFile.h \
    ../workdir/headerpp/Frameworks/AudioToolbox.framework/Headers/CAShow.h \
    ../workdir/headerpp/Frameworks/AudioToolbox.framework/Headers/CoreAudioClock.h \
    ../workdir/headerpp/Frameworks/AudioToolbox.framework/Headers/DefaultAudioOutput.h \
    ../workdir/headerpp/Frameworks/AudioToolbox.framework/Headers/ExtendedAudioFile.h \
    ../workdir/headerpp/Frameworks/AudioToolbox.framework/Headers/MusicDevice.h \
    ../workdir/headerpp/Frameworks/AudioToolbox.framework/Headers/MusicPlayer.h
