python extract.py \
    headerpp_cgpdf.json \
    ../dylib-hook/libhook.mm \
    ../../header-processing/cfgs/cgpdf_blacklist \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGAffineTransform.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGBase.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGBitmapContext.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGColor.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGColorConversionInfo.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGColorSpace.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGContext.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGDataConsumer.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGDataProvider.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGDirectDisplay.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGDirectDisplayMetal.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGDirectPalette.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGDisplayConfiguration.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGDisplayFade.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGDisplayStream.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGError.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGFont.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGFunction.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGGeometry.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGGradient.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGImage.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGLayer.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGPDFArray.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGPDFContentStream.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGPDFContext.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGPDFDictionary.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGPDFDocument.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGPDFObject.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGPDFOperatorTable.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGPDFPage.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGPDFScanner.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGPDFStream.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGPDFString.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGPSConverter.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGPath.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGPattern.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGRemoteOperation.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGSession.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGShading.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CoreGraphics.h 
