python extract.py \
    headerpp_cgfont.json \
    ../dylib-hook/libhook.mm \
    ../../header-processing/cfgs/font_blacklist \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGAffineTransform.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGBase.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGBitmapContext.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGColor.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGColorConversionInfo.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGColorSpace.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGContext.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGDataConsumer.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGDataProvider.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGDirectDisplay.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGDirectDisplayMetal.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGDirectPalette.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGDisplayConfiguration.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGDisplayStream.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGError.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGFont.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGFunction.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGGeometry.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGGradient.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGImage.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGLayer.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGPath.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGPattern.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGRemoteOperation.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGSession.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CGShading.h \
    ../workdir/headerpp/Frameworks/CoreGraphics.framework/Headers/CoreGraphics.h \
    ../workdir/headerpp/Frameworks/CoreText.framework/Headers/CTDefines.h \
    ../workdir/headerpp/Frameworks/CoreText.framework/Headers/CTFont.h \
    ../workdir/headerpp/Frameworks/CoreText.framework/Headers/CTFontCollection.h \
    ../workdir/headerpp/Frameworks/CoreText.framework/Headers/CTFontDescriptor.h \
    ../workdir/headerpp/Frameworks/CoreText.framework/Headers/CTFontManager.h \
    ../workdir/headerpp/Frameworks/CoreText.framework/Headers/CTFontManagerErrors.h \
    ../workdir/headerpp/Frameworks/CoreText.framework/Headers/CTFontTraits.h \
    ../workdir/headerpp/Frameworks/CoreText.framework/Headers/CTFrame.h \
    ../workdir/headerpp/Frameworks/CoreText.framework/Headers/CTFramesetter.h \
    ../workdir/headerpp/Frameworks/CoreText.framework/Headers/CTGlyphInfo.h \
    ../workdir/headerpp/Frameworks/CoreText.framework/Headers/CTLine.h \
    ../workdir/headerpp/Frameworks/CoreText.framework/Headers/CTParagraphStyle.h \
    ../workdir/headerpp/Frameworks/CoreText.framework/Headers/CTRun.h \
    ../workdir/headerpp/Frameworks/CoreText.framework/Headers/CTRunDelegate.h \
    ../workdir/headerpp/Frameworks/CoreText.framework/Headers/CTStringAttributes.h \
    ../workdir/headerpp/Frameworks/CoreText.framework/Headers/CTTextTab.h \
    ../workdir/headerpp/Frameworks/CoreText.framework/Headers/CTTypesetter.h \
    ../workdir/headerpp/Frameworks/CoreText.framework/Headers/CoreText.h \
    ../workdir/headerpp/Frameworks/CoreFoundation.framework/Headers/CFArray.h
